--- # Start

--- # change port
server:
  port: 8085

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false # ?? ?? reload
    prefix: classpath:/templates
    suffix: .html

--- # mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boot_st
    username: boot
    password: boot

--- #
spring:
  jpa:
    hibernate:
      ddl-auto: none #update
    properties:
      hibernate:
        show_sql : true
        format_sql: true

--- # encrypt
encrypt:
  key16: abcdefg123he334g
